title: Adam Schroeder
logo: /assets/img/logo.png
description: Supply Chain Analytics graduate student with experience in operations, technology, process improvement, and data-driven decision making.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
